### ISSUE TITLE
Postgres tests failed by ContextualVersionConflict.

### ISSUE THREAD

**Issue by monaka** [deis/wal-e#14]
I tried running test for deis/postgres (just forked. no modification) and got an error by Wal-e 

```
pkg_resources.ContextualVersionConflict: (google-gax 0.12.3 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('google-gax==0.12.2'), set(['gax-google-logging-v2', 'gax-google-pubsub-v1']))
```

Complete log is at https://travis-ci.org/monami-ya/postgres/builds/145157860

**Comment by monaka** [comment]
This issue can be fixed by patching Dockerfile in deis/postgres.
Which is bettter, here (requirements.txt) or there (Dockerfile)?

**Comment by bacongobbler** [comment]
patches are better here. Thanks!

**Comment by monaka** [comment]
@bacongobbler I sent PR #15. It works on my environment.

**Comment by monaka** [comment]
I close this issue as the PR #15 is merged.

**Comment by mboersma** [comment]
Thanks again for tracking this down and fixing it @monaka.
