### ISSUE TITLE
Start travis-CI

### ISSUE THREAD

**Issue by monaka** [deis/wal-e#7]
Another Deis components are using [Travis-CI](https://travis-ci.org/deis/) but WAL-E doesn't.
In my forked repository, some tests don't pass. And it seems some patches are available at the upstream.

**Comment by bacongobbler** [comment]
this fork was intended to only be short living since we required to upgrade to boto3 for minio support. I personally don't think it's worth it for the (short) time being.

**Comment by monaka** [comment]
Ok. I set Travis-CI on my repository up. It's enough for me.
