### ISSUE TITLE
Type error in Gevent.

### ISSUE THREAD

**Issue by monaka** [deis/wal-e#9]
I got some error messages when I run test on Travis-CI.
Are they expcted? Whole log is at https://travis-ci.org/monami-ya/wal-e/builds/139064144

These error are not shown on the upstream/master.

```
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/logging/handlers.py", line 863, in emit
    self.socket.sendto(msg, self.address)
  File "/home/travis/build/monami-ya/wal-e/.tox/boto-tip-2.7/lib/python2.7/site-packages/gevent/_socket2.py", line 418, in sendto
    return sock.sendto(*args)
TypeError: getsockaddrarg: AF_INET address must be tuple, not LocalPath
Logged from file connectionpool.py, line 203
```

**Comment by bacongobbler** [comment]
not expected, but also completely unrelated. That error is coming from gevent, not wal-e. Please file bugs upstream.

**Comment by monaka** [comment]
I agree the place is not in WAL-E. But the upstream/mater doesn't show this error.
So this issue may be Deis's side.
